"""add webhook endpoint secret

Revision ID: bf64d936ba22
Revises: bb85038d0fc1
Create Date: 2026-09-05 01:48:15.477019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf64d936ba22'
down_revision: Union[str, Sequence[str], None] = 'bb85038d0fc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webhook_endpoints', sa.Column('secret', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('webhook_endpoints', 'secret')
    # ### end Alembic commands ###
